version: "3"

volumes:
  db-volume:

services:

 web:
   ports:
     - "8080:80"
   build: ./docker/web
   container_name: web
   volumes:
     - ./src:/var/www/html

 db:
   image: mysql:8.0
   container_name: db
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: timecard
     MYSQL_USER: timecard
     MYSQL_PASSWORD: password
     TZ: 'Asia/Tokyo'

   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
   volumes:
     - db-volume:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 4306:3306